# Generated by Django 4.2.4 on 2023-08-19 20:27

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphid', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('climates', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=1000, size=None)),
                ('diameter', models.IntegerField(blank=True, null=True)),
                ('gravity', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('orbitalPeriod', models.IntegerField(blank=True, null=True)),
                ('population', models.CharField(blank=True, max_length=100, null=True)),
                ('rotationPeriod', models.IntegerField(blank=True, null=True)),
                ('surfaceWater', models.FloatField(blank=True, null=True)),
                ('terrains', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphid', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('mglt', models.IntegerField()),
                ('cargoCapacity', models.FloatField()),
                ('consumables', models.CharField(max_length=100)),
                ('costInCredits', models.FloatField()),
                ('crew', models.IntegerField()),
                ('hyperdriveRating', models.FloatField()),
                ('length', models.FloatField()),
                ('manufacturer', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=1000, size=None)),
                ('maxAtmospheringSpeed', models.IntegerField()),
                ('model', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('passengers', models.CharField(max_length=100)),
                ('starshipClass', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphid', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('cargoCapacity', models.FloatField()),
                ('consumables', models.CharField(max_length=100)),
                ('costInCredits', models.FloatField()),
                ('crew', models.IntegerField()),
                ('length', models.FloatField()),
                ('manufacturer', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=1000, size=None)),
                ('maxAtmospheringSpeed', models.IntegerField()),
                ('model', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('passengers', models.CharField(max_length=100)),
                ('vehicleClass', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphid', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('averageHeight', models.FloatField()),
                ('averageLifespan', models.IntegerField()),
                ('classification', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('eyeColors', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=1000, size=None)),
                ('hairColors', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=1000, size=None)),
                ('language', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('skinColors', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=1000, size=None)),
                ('homeworld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.planet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphid', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('birthYear', models.IntegerField()),
                ('eyeColor', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('hairColor', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('mass', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('skinColor', models.CharField(max_length=100)),
                ('homeworld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.planet')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.specie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphid', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('director', models.CharField(max_length=100)),
                ('episodeId', models.IntegerField(null=True)),
                ('openingCrawl', models.TextField()),
                ('producers', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=1000, size=None)),
                ('releaseDate', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('characters', models.ManyToManyField(to='api.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
