# Generated by Django 4.2.4 on 2023-08-19 22:05

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_specie_averageheight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='terrains',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, max_length=1000, null=True, size=None),
        ),
    ]
