# Generated by Django 4.2.4 on 2023-08-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_vehicle_pilotconnection_alter_vehicle_cargocapacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='manufacturer',
            new_name='manufacturers',
        ),
    ]
