# Generated by Django 4.2.4 on 2023-08-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_vehicle_pilotconnection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starship',
            old_name='mglt',
            new_name='MGLT',
        ),
        migrations.RenameField(
            model_name='starship',
            old_name='manufacturer',
            new_name='manufacturers',
        ),
    ]
