# Generated by Django 4.2.4 on 2023-08-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_mglt_starship_mglt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starship',
            name='crew',
            field=models.CharField(max_length=20),
        ),
    ]
