# Generated by Django 4.2.4 on 2023-08-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_starship_mglt_alter_starship_cargocapacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='starship',
            name='pilotConnection',
            field=models.ManyToManyField(to='api.person'),
        ),
    ]
