# Generated by Django 4.2.4 on 2023-08-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_starship_pilotconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='planetConnection',
            field=models.ManyToManyField(to='api.planet'),
        ),
        migrations.AddField(
            model_name='film',
            name='speciesConnection',
            field=models.ManyToManyField(to='api.specie'),
        ),
        migrations.AddField(
            model_name='film',
            name='starshipConnection',
            field=models.ManyToManyField(to='api.starship'),
        ),
        migrations.AddField(
            model_name='film',
            name='vehicleConnection',
            field=models.ManyToManyField(to='api.vehicle'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='openingCrawl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='releaseDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
