# Generated by Django 4.2.4 on 2023-08-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_episodeid_film_episodeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='characters',
            new_name='characterConnection',
        ),
    ]
